// Demo data for the cemetery management system
// This provides realistic sample data for demonstration purposes

export const demoWorkOrders = [
  {
    id: '1',
    title: 'Lawn maintenance - Section A',
    description: 'Weekly mowing and trimming of grass in Section A. Includes edging around headstones.',
    type: 'grounds',
    priority: 'medium',
    status: 'in_progress',
    assigned_to: 'John Smith',
    assigned_to_name: 'John Smith',
    due_date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '2',
    title: 'Repair grave marker - Lot 42',
    description: 'Granite marker has shifted and needs realignment. Family requested repair by end of month.',
    type: 'repair',
    priority: 'high',
    status: 'pending',
    assigned_to: 'Mike Johnson',
    assigned_to_name: 'Mike Johnson',
    due_date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '3',
    title: 'Prepare burial site - Lot 156',
    description: 'Opening for Williams family burial scheduled for Friday at 2pm.',
    type: 'burial_prep',
    priority: 'urgent',
    status: 'pending',
    assigned_to: 'Grounds Crew',
    assigned_to_name: 'Grounds Crew',
    due_date: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    title: 'Tree trimming - Main entrance',
    description: 'Overgrown branches blocking signage. Need professional arborist.',
    type: 'maintenance',
    priority: 'low',
    status: 'completed',
    assigned_to: 'External Contractor',
    assigned_to_name: 'External Contractor',
    due_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '5',
    title: 'Irrigation system check',
    description: 'Annual inspection of sprinkler system before summer season.',
    type: 'maintenance',
    priority: 'medium',
    status: 'completed',
    assigned_to: 'John Smith',
    assigned_to_name: 'John Smith',
    due_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const demoGrants = [
  {
    id: '1',
    title: 'Historic Cemetery Preservation Grant',
    description: 'Federal grant for maintenance and restoration of historic cemetery sites. Covers monument restoration, pathway repairs, and documentation.',
    type: 'grant',
    source: 'National Trust for Historic Preservation',
    amount: 25000,
    deadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'available',
    application_date: null,
    notes: 'Requires 501(c)(3) status. Strong candidate based on our historic designation.',
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '2',
    title: 'Veterans Memorial Beautification Fund',
    description: 'State funding for improvements to veteran burial sections including new flags, markers, and landscaping.',
    type: 'benefit',
    source: 'Michigan Dept. of Veterans Affairs',
    amount: 15000,
    deadline: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'applied',
    application_date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    notes: 'Application submitted. Expecting response within 6 weeks.',
    created_at: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '3',
    title: 'Green Cemetery Initiative',
    description: 'Environmental grant for implementing eco-friendly burial options and sustainable groundskeeping practices.',
    type: 'opportunity',
    source: 'Green Burial Council',
    amount: 10000,
    deadline: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'available',
    application_date: null,
    notes: 'New opportunity - requires commitment to green burial practices.',
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '4',
    title: 'Community Heritage Foundation Grant',
    description: 'Local foundation supporting community landmarks and historical sites.',
    type: 'grant',
    source: 'Detroit Community Foundation',
    amount: 8500,
    deadline: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'approved',
    application_date: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    notes: 'Approved! Funds to be disbursed next quarter.',
    created_at: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '5',
    title: 'Accessibility Improvement Grant',
    description: 'ADA compliance funding for pathway improvements and accessibility features.',
    type: 'grant',
    source: 'Michigan DHHS',
    amount: 20000,
    deadline: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'received',
    application_date: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
    notes: 'Funds received. Project completion due in 12 months.',
    created_at: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const demoStats = {
  activeWorkOrders: 3,
  completedThisMonth: 12,
  pendingGrants: 2,
  grantFundsReceived: 28500,
  upcomingBurials: 2,
  totalCustomers: 847,
  inventoryAlerts: 3,
  revenueThisMonth: 45250,
};
