/**
 * Pre-need and at-need contracts, plus their payment schedules.
 *
 * Payment schedule lives here rather than in its own module because it is only
 * ever read through a contract.
 *
 * @see ./_shared for the pieces every module here shares.
 */
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { supabase } from '../../lib/supabase';
import { toCamelCaseKeys, toSnakeCaseKeys } from '../../lib/utils';
import { queryKeys } from '../../lib/query';
import { affectedRows, WriteBlockedError } from '../../lib/writeResult';
import type { TablesInsert } from '../../types/database';
import type { Contract, ContractItem, PaymentScheduleEntry } from '../../types';
import { type MutationCallbacks, type CreateInput, type UpdateInput, fromRows, mutationSideEffects, sb } from './_shared';

// ============================================
// CONTRACTS
// ============================================

type ContractRow = Record<string, unknown> & { contract_items?: Record<string, unknown>[] };

function mapContract(row: ContractRow): Contract {
  const { contract_items, ...rest } = row;
  return {
    ...toCamelCaseKeys(rest as Record<string, unknown>),
    items: (contract_items ?? []).map(item => toCamelCaseKeys(item as Record<string, unknown>)),
  } as unknown as Contract;
}

export function useContracts() {
  return useQuery({
    queryKey: queryKeys.contracts.list(),
    queryFn: async () => {
      const rows = await sb(
        supabase.from('contracts').select('*, contract_items(*)').order('created_at', { ascending: false })
      );
      return (rows as ContractRow[]).map(mapContract);
    },
  });
}

// Build contract_items insert rows from camelCase ContractItem input, dropping
// any client-side id (real ids are generated by the DB) and binding contractId.
function itemRows(
  items: ContractItem[] | undefined,
  contractId: string
): TablesInsert<'contract_items'>[] {
  return (items ?? []).map(({ id: _id, ...item }) => ({
    ...toSnakeCaseKeys(item),
    contract_id: contractId,
  }));
}

export function useCreateContract(callbacks?: MutationCallbacks<Contract>) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (data: CreateInput<Contract>) => {
      const { items, ...contractData } = data;
      const inserted = await sb(
        supabase.from('contracts')
          .insert(toSnakeCaseKeys(contractData))
          .select().single()
      ) as Record<string, unknown>;
      const contractId = inserted.id as string;

      const rows = itemRows(items, contractId);
      if (rows.length > 0) {
        await sb(supabase.from('contract_items').insert(rows).select());
      }

      const row = await sb(
        supabase.from('contracts').select('*, contract_items(*)').eq('id', contractId).single()
      );
      return mapContract(row as ContractRow);
    },
    ...mutationSideEffects(queryClient, queryKeys.contracts.all, callbacks),
  });
}

export function useUpdateContract(callbacks?: MutationCallbacks<Contract>) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async ({ id, items, ...data }: UpdateInput<Contract>) => {
      affectedRows(
        await sb(
          supabase.from('contracts')
            .update(toSnakeCaseKeys(data))
            .eq('id', id).select()
        ),
        'update'
      );

      // When items are supplied, replace the contract's line items wholesale.
      // Nothing references contract_items.id, so a delete-then-insert is safe
      // and keeps the persisted set in sync with what the form submitted.
      if (items !== undefined) {
        // This clear-then-insert needs DELETE on contract_items, which only an
        // admin has. A `staff` user can UPDATE the contract itself, so without
        // this check the delete would quietly remove nothing, the insert would
        // succeed, and the contract would end up with every line item twice.
        //
        // `affectedRows` cannot be used directly here: a contract legitimately
        // may have no items, and then zero deleted rows is the correct outcome.
        // So the count is compared against what is actually there.
        const existing = await sb(
          supabase.from('contract_items').select('id').eq('contract_id', id)
        ) as unknown[];
        if (existing.length > 0) {
          const removed = await sb(
            supabase.from('contract_items').delete().eq('contract_id', id).select('id')
          ) as unknown[];
          if (removed.length !== existing.length) {
            throw new WriteBlockedError(
              'The contract was saved, but its line items could not be replaced — only administrators can remove line items. Ask an administrator to make this change.'
            );
          }
        }
        const rows = itemRows(items, id);
        if (rows.length > 0) {
          await sb(supabase.from('contract_items').insert(rows).select());
        }
      }

      const row = await sb(
        supabase.from('contracts').select('*, contract_items(*)').eq('id', id).single()
      );
      return mapContract(row as ContractRow);
    },
    ...mutationSideEffects(queryClient, queryKeys.contracts.all, callbacks),
  });
}

export function useDeleteContract(callbacks?: MutationCallbacks<{ success: boolean }>) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (id: string) => {
      // `.select()` so rows come back: an RLS-refused delete is a 200 with
      // zero rows, not an error. See `lib/writeResult`.
      const rows = await sb(supabase.from('contracts').delete().eq('id', id).select('id'));
      affectedRows(rows, 'delete');
      return { success: true };
    },
    ...mutationSideEffects(queryClient, queryKeys.contracts.all, callbacks),
  });
}

// ============================================
// PAYMENT SCHEDULE
// ============================================

export function usePaymentSchedule(contractId: string) {
  return useQuery({
    queryKey: queryKeys.paymentSchedule.byContract(contractId),
    queryFn: async () => {
      const rows = await sb(
        supabase.from('payment_schedule').select('*')
          .eq('contract_id', contractId)
          .order('due_date', { ascending: true })
      );
      return fromRows<PaymentScheduleEntry>(rows);
    },
    enabled: !!contractId,
  });
}
